# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hackatalk server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build
      run: |
        pushd ./server
        export DATABASE_URL=${{ secrets.AZURE_DB_URL }}
        npm install
        npm run build --if-present
        npm run migrate:up --if-present
        popd

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'hackatalk'
        # slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b693f51c7f24d7eacd53ae7c7fcee7f }}
        package: ./server
